sudo: required  # because we're using apt
dist: trusty

language: node_js
node_js:
  - 6.9.1

apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable

cache: yarn
addons:
  apt:
    sources:
      - sourceline: 'deb https://dl.yarnpkg.com/debian/ stable main'
        key_url: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    packages:
      - yarn

before_install:
 - export CHROME_BIN=/usr/bin/google-chrome
 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start
 - sudo apt-get update
 - sudo apt-get install -y libappindicator1 fonts-liberation
 - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
 - sudo dpkg -i google-chrome*.deb
 - rm google-chrome*.deb

install:
  - (cd webapp; yarn)
  - (cd functions; yarn)

script:
  - if [ "$TRAVIS_BRANCH" = "staging" ]; then export WEB_ENV=staging; fi
  - if [ "$TRAVIS_BRANCH" = "master" ]; then export WEB_ENV=prod; fi
  - (cd webapp; ng test --watch false && ng build --environment=$WEB_ENV)
  - (cd functions; yarn test)

deploy:
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "$FIREBASE_TOKEN"
    project: hubbub-159904
    on:
      branch: master
  - provider: firebase
    skip_cleanup: true
    token:
      secure: "$FIREBASE_STAGING_TOKEN"
    project: hubbub-staging
    on:
      branch: staging

