# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Hubbub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hubbub
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'p2.OAuth2', '~> 3.0'

  target 'HubbubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HubbubUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
