# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Hubbub' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hubbub
  pod 'Alamofire', '~> 4.4'
  pod 'AlamofireImage', '~> 3.1'
  pod 'Firebase/Auth'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Database'
  pod 'p2.OAuth2', '~> 3.0'
  pod 'SnapKit', '~> 3.0'

  # Pods for Crashlytics
  pod 'Fabric'
  pod 'Crashlytics'

  target 'HubbubTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'HubbubUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
